#!/usr/bin/env python3
"""Generate a Mermaid route diagram from the FastAPI router table."""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root. Defaults to the parent of scripts/.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output file. Defaults to docs/diagrams/generated/api-routes.mmd.",
    )
    return parser.parse_args()


def add_import_paths(repo_root: Path) -> None:
    for path in (
        repo_root / "apps" / "api",
        repo_root / "packages" / "x12-edi-tools" / "src",
    ):
        sys.path.insert(0, str(path))


def node_id(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]+", "_", value).strip("_")
    return normalized or "route"


def mermaid_label(value: str) -> str:
    return value.replace('"', "'")


def first_line(value: str | None) -> str:
    if not value:
        return ""
    return value.strip().splitlines()[0].strip()


def generate_diagram(repo_root: Path) -> str:
    os.environ.setdefault("X12_API_REPO_ROOT", str(repo_root))
    os.environ.setdefault("X12_API_DEPLOYMENT_TARGET", "lambda")
    add_import_paths(repo_root)

    from fastapi.routing import APIRoute  # noqa: PLC0415

    from app.main import app  # noqa: PLC0415

    routes_by_tag: dict[str, list[tuple[str, str, str]]] = {}
    for route in app.routes:
        if not isinstance(route, APIRoute) or not route.include_in_schema:
            continue
        tag = str(route.tags[0]) if route.tags else "root"
        methods = sorted(
            method for method in route.methods if method not in {"HEAD", "OPTIONS"}
        )
        purpose = first_line(route.description) or route.summary or route.name
        for method in methods:
            routes_by_tag.setdefault(tag, []).append((method, route.path, purpose))

    lines = [
        "%% Generated by scripts/generate_route_diagram.py; do not edit.",
        "flowchart LR",
        '  client["Browser or API client"] --> edge["CloudFront /api/* behavior"]',
        '  edge --> app["FastAPI app on Lambda"]',
    ]
    for tag in sorted(routes_by_tag):
        subgraph_id = f"group_{node_id(tag)}"
        lines.append(f'  subgraph {subgraph_id}["{mermaid_label(tag)}"]')
        for method, path, purpose in sorted(
            routes_by_tag[tag], key=lambda item: (item[1], item[0])
        ):
            route_id = f"route_{node_id(method + '_' + path)}"
            label = mermaid_label(f"{method} {path}<br/>{purpose}")
            lines.append(f'    {route_id}["{label}"]')
        lines.append("  end")
        for method, path, _purpose in sorted(
            routes_by_tag[tag], key=lambda item: (item[1], item[0])
        ):
            route_id = f"route_{node_id(method + '_' + path)}"
            lines.append(f"  app --> {route_id}")

    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    output = (
        args.output or repo_root / "docs" / "diagrams" / "generated" / "api-routes.mmd"
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate_diagram(repo_root), encoding="utf-8")
    print(f"Generated {output.relative_to(repo_root)}")


if __name__ == "__main__":
    main()
